version: "3.8"
services:
  master1:
    image: cloudbees/cloudbees-core-cm:latest
    container_name: cb-master1
    user: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    links:
      - cjoc:cjoc.cb-local.de
      - agent1:agent1.cb-local.de
    volumes:
      - ./jenkins-data:/var/jenkins_home
#   - /home/andi/.m2:/var/jenkins_home/.m2
#      - ssh:/var/jenkins_home/.ssh


  cjoc:
    image: cloudbees/cloudbees-core-oc:latest
    container_name: cjoc
    user: root
    ports:
      - "8081:8080"
      - "50002:50000"
    links:
     # - master1:master.cb-local.de
      - agent1:agent1.cb-local.de
    volumes:
      - ./jenkins-data-oc:/var/jenkins_home
#   - /home/andi/.m2:/var/jenkins_home/.m2
#      - ssh:/var/jenkins_home/.ssh


  agent1:
    image: jenkins/ssh-slave:latest
    container_name: agent1
#    user: root
    ports:
      - "2222:22"
    environment:
      JENKINS_SLAVE_SSH_PUBKEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0smsRx4AD0Aek3TKp4D2G/SjS6Bm3SHnI0boBPGLXfgMDP7jaNWjbgEzS79hN6HcFXZS+u4zMotN7gA5f26Hl/H3XPEcqtyodewlIC0JB1QFMbAi3k7Pr0irh8L0bmFgORb1YHV8XwZcrznXNPdSfzKonEV7zuXORK1n9VWmQs6WpL4Ay6440u6iXXvbcSav1l1uAvJ4lMfdq/KOWTyZ4RIHejgqsp88l58ZAtCGbDXr81gbjCbLTuGxWBV5N2wgMRJQ/uoqvXZu+rkHtwf861WvQ3jT1obiwXwljLz46WlWism3r+ZV/2Kmz1VYfc3dl/p2izeDROUpHiWIFrIAcsfr7Wk6AP8Hdg533geFLS72LnMrzHX1zYL1AEmH2fy3hpWCoM8X1E81sjCXoYZLnSnhpquUWDVTZvYzkzBmbVBR9xb1Eg+wRNz7DVkDz40d+lHEbutWPjdT1BSYF6eJJhe+rUGhYD70Obmtho5gEbJ2rMPLkTPM0/+u+OerzeIpyMOdMWKoRX7RXT6G3yFTYv07ax5dnfCPaqopV3n5SVlM+3czL6/Rb8U2C/pd70bUprpYXfAaH7+ftrssT1F3pBof6e/mVjWZrZcJK8LyvFuFGkb8gZ6IVxn2VE5dkiQUjaJpJjQ/132qB9i12UZ1d853RCUmdzJBvbgmQPngVgw== acaternberg@cloudbees.com"
      JAVA_HOME: "/usr/local/openjdk-8/"


#docker run --name mynginx2 --mount type=bind,source=/var/www,target=/usr/share/nginx/html,readonly --mount source=/var/nginx/conf,target=/etc/nginx/conf,readonly -p 80:80 -d nginx
  cb-local:
    image: nginx:latest
    container_name: cb_nginx
    volumes:
      - ./nginx-config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config/etc/nginx/conf.d/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
#      - ./nginx-config/cert/star_xx_com.pem:/etc/nginx/cert/star_xx_com.pem
#      - ./nginx-config/cert/star_xx_com.key:/etc/nginx/cert/star_xx_com.key
#      - ./nginx-config/cert/star_xx_com.crt:/etc/nginx/cert/star_xx_com.crt
    ports:
      - 80:80
#      - 443:443
    links:
        - master1:master.cb-local.de
        - cjoc:cjoc.cb-local.de

##Ubuntu GUI
#docker run -p 6080:80 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
#  browser:
#    image: dorowu/ubuntu-desktop-lxde-vnc
#    container_name: ubuntu
#    user: root
#    ports:
#      - "6080:80"
#    links:
#      - master1:master1
#      - cjoc:cjoc
#      - agent1:agent1
